# Generated by Django 5.2.17 on 2026-09-12 14:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, help_text='Recommended 1600 x 700 px.', upload_to='banners/')),
                ('button_text', models.CharField(blank=True, default='Shop now', max_length=40)),
                ('button_url', models.CharField(blank=True, default='/products/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('body', models.TextField(help_text='HTML is allowed. Only trusted staff should edit this content.')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_footer', models.BooleanField(default=True)),
                ('show_in_nav', models.BooleanField(default=False, verbose_name='Show in main navigation')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Venture Arabia Trading Services', max_length=120)),
                ('tagline', models.CharField(default='Authorised Trodat stamp dealer in Doha since 2009 - rubber stamps, toners, printing & office services.', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='PNG or SVG, ideally with a transparent background.', upload_to='branding/')),
                ('legal_name', models.CharField(default='Venture Arabia Trading Services', max_length=200)),
                ('commercial_registration', models.CharField(blank=True, help_text='Shown in the footer and on invoices. Required for online trading in Qatar.', max_length=50, verbose_name='Commercial Registration (CR) number')),
                ('trade_licence', models.CharField(blank=True, max_length=50, verbose_name='Trade licence number')),
                ('po_box', models.CharField(default='201678', max_length=30, verbose_name='P.O. Box')),
                ('building', models.CharField(default='Building No. 441, Office No. 2, First Floor', max_length=60)),
                ('zone', models.CharField(default='Zone 56', max_length=20)),
                ('street', models.CharField(default='Street 340', max_length=60)),
                ('landmark', models.CharField(default='Near Al Ahli Bank building', max_length=120)),
                ('area', models.CharField(default='Salwa Road', max_length=120)),
                ('city', models.CharField(default='Doha', max_length=60)),
                ('country', models.CharField(default='Qatar', max_length=60)),
                ('google_maps_embed_url', models.URLField(blank=True, help_text="Optional 'Embed a map' URL from Google Maps (the src of the iframe).")),
                ('google_maps_link', models.URLField(blank=True, help_text="Optional 'Share' link to open the location in Google Maps.")),
                ('phone', models.CharField(default='+974 4468 9269', max_length=30)),
                ('mobile_1', models.CharField(default='+974 5588 3587', max_length=30)),
                ('mobile_2', models.CharField(blank=True, default='+974 3390 5158', max_length=30)),
                ('whatsapp_number', models.CharField(default='97455883587', help_text='Digits only, with country code and no plus sign, e.g. 97455883587.', max_length=20)),
                ('email', models.EmailField(default='venture@venture.com.qa', max_length=254)),
                ('email_secondary', models.EmailField(blank=True, default='venstationery@gmail.com', max_length=254)),
                ('opening_hours', models.TextField(default='Saturday - Thursday: 8:00 AM - 1:00 PM, 4:00 PM - 9:00 PM\nFriday: Closed', help_text='One line per entry.')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('currency_code', models.CharField(default='QAR', max_length=3)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='Set to 0 to disable free delivery.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Free delivery for orders above')),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Qatar currently applies no VAT on these goods. Update here if legislation changes.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tax / VAT rate (%)')),
                ('enable_cash_on_delivery', models.BooleanField(default=True)),
                ('enable_bank_transfer', models.BooleanField(default=True)),
                ('enable_card_on_delivery', models.BooleanField(default=True, verbose_name='Enable card payment on delivery (POS machine)')),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_account_name', models.CharField(blank=True, max_length=120)),
                ('bank_iban', models.CharField(blank=True, max_length=40, verbose_name='IBAN')),
                ('bank_instructions', models.TextField(blank=True, default='Please transfer the total amount and send the transfer receipt to our WhatsApp with your order number.')),
                ('announcement_bar', models.CharField(blank=True, default='Free collection & delivery within Doha | Special photocopy rates for schools, colleges and corporate offices', max_length=200)),
                ('about_text', models.TextField(default='Venture Arabia Trading Services has been an authorised Trodat stamps dealer in Qatar since 2009. We manufacture all types of rubber and self-inking stamps, supply computer toners and accessories, and provide printing, photocopying, laminating and binding services with free collection and delivery.')),
                ('footer_text', models.CharField(blank=True, default='All prices are in Qatari Riyal (QAR).', max_length=250)),
                ('meta_description', models.CharField(default='Trodat stamps, rubber stamps, toners, printing, photocopying, laminating and binding in Doha, Qatar. Free collection and delivery.', max_length=160)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('organisation', models.CharField(blank=True, max_length=120)),
                ('quote', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
