# Generated by Django 5.2.17 on 2026-09-12 17:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(default='Venture Arabia Trading Services has been a Trodat stamps dealer in Qatar since 2009. We manufacture all types of rubber and self-inking stamps, supply computer toners and accessories, and provide printing, photocopying, laminating and binding services with free collection and delivery across Doha.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='announcement_bar',
            field=models.CharField(blank=True, default='Free collection & delivery across Doha | Special photocopy rates for schools, colleges and corporate offices', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 = free delivery.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Only used when a delivery fee is set. 0 = no threshold.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Free delivery for orders above'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(default='Trodat stamps, rubber stamps, toners, printing, photocopying, laminating and binding in Doha, Qatar. Delivery across Doha.', max_length=160),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='opening_hours',
            field=models.TextField(default='Saturday - Thursday: 9:00 AM - 1:00 PM, 4:00 PM - 8:00 PM\nFriday: Closed', help_text='One line per entry.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='Trodat stamp dealer in Doha since 2009 - rubber stamps, toners, printing & office services.', max_length=200),
        ),
    ]
