# Generated by Django 5.2.17 on 2026-09-12 14:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('delivery_method', models.CharField(choices=[('delivery', 'Home / office delivery'), ('pickup', 'Collect from our office (Salwa Road)')], default='delivery', max_length=20)),
                ('building', models.CharField(blank=True, max_length=120)),
                ('zone', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(blank=True, max_length=60)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, default='Doha', max_length=60)),
                ('delivery_notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on delivery'), ('card_on_delivery', 'Card on delivery (POS)'), ('bank_transfer', 'Bank transfer')], default='cod', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='QAR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('processing', 'In production / processing'), ('ready', 'Ready for collection'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered / collected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes - never shown to the customer.')),
                ('accepted_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=60)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('custom_text', models.TextField(blank=True, help_text='Stamp text or customisation instructions supplied by the customer.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product')),
            ],
        ),
    ]
