# Generated by Django 5.2.17 on 2026-09-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Empty = price to be confirmed with the customer.', max_digits=10, null=True),
        ),
    ]
