# Generated by Django 5.2.17 on 2026-09-12 14:08

import catalog.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('icon', models.CharField(choices=[('stamp', 'Stamp'), ('print', 'Printer'), ('copy', 'Photocopier'), ('laminate', 'Laminating'), ('bind', 'Binding'), ('toner', 'Toner'), ('delivery', 'Delivery van'), ('design', 'Design')], default='print', max_length=20)),
                ('short_description', models.CharField(max_length=250)),
                ('description', models.TextField(help_text='Plain text. Blank lines start a new paragraph.')),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Starting price (QAR)')),
                ('price_unit', models.CharField(blank=True, help_text='e.g. per page, per stamp, per document', max_length=40)),
                ('turnaround', models.CharField(blank=True, help_text='e.g. Same day, 1-2 working days', max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='services/')),
                ('is_featured', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='categories/')),
                ('icon', models.CharField(blank=True, help_text='Optional emoji or short label shown when no image is set, e.g. 🖃', max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('sku', models.CharField(help_text='e.g. 4912', max_length=60, unique=True, verbose_name='SKU / model number')),
                ('brand', models.CharField(blank=True, default='Trodat', max_length=60)),
                ('short_description', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True, help_text='Plain text. Blank lines start a new paragraph.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (QAR)')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Shown crossed out to indicate a discount.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Compare-at price (QAR)')),
                ('track_stock', models.BooleanField(default=False, help_text='Untick for made-to-order items such as custom stamps.')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('plate_size', models.CharField(blank=True, help_text='e.g. 47 mm x 18 mm', max_length=60, verbose_name='Max. text plate size')),
                ('ink_cartridge', models.CharField(blank=True, help_text='e.g. 6/4912', max_length=60, verbose_name='Replacement ink cartridge')),
                ('date_size', models.CharField(blank=True, help_text='For daters, e.g. 4 mm', max_length=30)),
                ('available_colours', models.CharField(blank=True, help_text='Comma separated, e.g. Black, Blue, Red', max_length=200, verbose_name='Body colours')),
                ('ink_colours', models.CharField(blank=True, default='Black, Blue, Red, Green, Violet', help_text='Comma separated', max_length=200)),
                ('is_customisable', models.BooleanField(default=False, help_text='If ticked, customers must enter the stamp text or upload artwork when ordering.', verbose_name='Requires custom text / artwork')),
                ('customisation_help', models.CharField(blank=True, default='Enter the exact text for your stamp (line by line). We will send you a proof before production.', max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('quantity', models.CharField(blank=True, help_text='e.g. 500 pages, 3 stamps', max_length=60)),
                ('details', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='quotes/%Y/%m/', validators=[catalog.validators.validate_upload])),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quote sent'), ('won', 'Won'), ('closed', 'Closed')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='catalog.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='catalog_pro_is_acti_e6e001_idx'),
        ),
    ]
