# Generated by Django 5.2.17 on 2026-09-12 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Leave empty to show 'Price on request' - the price is then confirmed with the customer before production.", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (QAR)'),
        ),
    ]
